### PR TITLE
Fix .NET 4.7.2 on Win7 TLS compatibility

### PR DESCRIPTION
**Pull request by imba-tjd**
- [x] [Searched](https://github.com/shadowsocks/shadowsocks-windows/search?q=is%3Apr&type=Issues) for similar pull requests
- [x] Compiled the code with Visual Studio

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New feature

Fix https://github.com/shadowsocks/shadowsocks-windows/issues/2471

混个contributor _(:з」∠) 如果位置不合适就告诉我来改

### CODE REVIEW

**Comment by celeron533** [comment]
checked some common web sites:
```
github:
Connection - secure connection settings
The connection to this site is encrypted and authenticated using TLS 1.3, X25519, and AES_128_GCM.

bilibili:
Connection - secure connection settings
The connection to this site is encrypted and authenticated using TLS 1.2, ECDHE_RSA with P-256, and AES_128_GCM.

bing:
Connection - secure connection settings
The connection to this site is encrypted and authenticated using TLS 1.2, ECDHE_RSA with X25519, and AES_128_GCM.

stackoverflow:
Connection - secure connection settings
The connection to this site is encrypted and authenticated using TLS 1.2, ECDHE_RSA with X25519, and AES_128_GCM.

ebay:
Connection - secure connection settings
The connection to this site is encrypted and authenticated using TLS 1.2, ECDHE_RSA with P-256, and AES_128_GCM.
```

**Comment by celeron533** [comment]
https://stackoverflow.com/questions/28286086/default-securityprotocol-in-net-4-5/36454717#36454717

**Comment by imba-tjd** [comment]
我的想法是只留TLS 1.2和1.3……您的意思是改成

```C#
System.Net.ServicePointManager.SecurityProtocol |= 
    SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;
```

？

**Comment by celeron533** [comment]
谢谢 @imba-tjd 
这个已经够用，不太需要检测系统版本
```
System.Net.ServicePointManager.SecurityProtocol |= 
    SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12
```

唯一的遗憾就是vista只能手动再见了。

**Comment by imba-tjd** [comment]
好了~

**Pull request merged**
