### PR TITLE
Update PAC to handle user rules in a better way

### PR DESCRIPTION
**Pull request by celeron533**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

- [x] [Searched](https://github.com/shadowsocks/shadowsocks-windows/search?q=is%3Apr&type=Issues) for similar pull requests
- [x] Compiled the code with Visual Studio

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New feature

---

### Description of your *pull request* and other information

- Update the PAC javascript to support user rules in a better way: PAC will check the user rules first to find whether the URL should be connected via PROXY or DIRECT. If it does not match, then go to check GFWList rules.
- Update the embedded PAC file with updated PAC template and latest gfwlist

### CODE REVIEW

**Comment by chenshaoju** [comment]
Test failed, Base AppVeyor 4.1.4.6 version, On Windows 7 & Windows 10.

```
---------------------------
Shadowsocks non-UI Error
---------------------------
非预期错误，Shadowsocks将退出。请提交此错误到 https://github.com/shadowsocks/shadowsocks-windows/issues  System.TypeInitializationException: “Shadowsocks.Controller.AvailabilityStatistics”的类型初始值设定项引发异常。 ---> System.IO.FileNotFoundException: 未能加载文件或程序集“Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed”或它的某一个依赖项。系统找不到指定的文件。    在 Shadowsocks.Model.Configuration.Load()    在 Shadowsocks.Util.Utils.GetTempPath()    在 Shadowsocks.Util.Utils.GetTempPath(String filename)    在 Shadowsocks.Controller.AvailabilityStatistics..cctor()    --- 内部异常堆栈跟踪的结尾 ---    在 Shadowsocks.Controller.AvailabilityStatistics.get_Instance()    在 Shadowsocks.Controller.ShadowsocksController..ctor()    在 Shadowsocks.Program.Main(String[] args)
---------------------------
确定   
---------------------------
```

**Comment by studentmain** [comment]
有点意思，修PAC炸统计

**Comment by celeron533** [comment]
>有点意思，修PAC炸统计

西边不亮东边亮

**Comment by celeron533** [comment]
```
非预期错误，Shadowsocks将退出。
请提交此错误到 https://github.com/shadowsocks/shadowsocks-windows/issues  System.TypeInitializationException: 
“Shadowsocks.Controller.AvailabilityStatistics”的类型初始值设定项引发异常。 
---> System.IO.FileNotFoundException: 未能加载文件或程序集“Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed”或它的某一个依赖项。系统找不到指定的文件。
    在 Shadowsocks.Model.Configuration.Load()
    在 Shadowsocks.Util.Utils.GetTempPath()
    在 Shadowsocks.Util.Utils.GetTempPath(String filename)
    在 Shadowsocks.Controller.AvailabilityStatistics..cctor()
    --- 内部异常堆栈跟踪的结尾 ---
    在 Shadowsocks.Controller.AvailabilityStatistics.get_Instance()
    在 Shadowsocks.Controller.ShadowsocksController..ctor()
    在 Shadowsocks.Program.Main(String[] args)
```

在这个 pull request 之前有更新过所有的nuget包。
7194f5ab71ae116b2d5b841354ea98f17146c846


发生错误的操作是？

**Comment by chenshaoju** [comment]
目前没编译环境，有环境了我测试一下。

**Comment by chenshaoju** [comment]
Base AppVeyor 4.1.4.9 version test has passed, On Windows 7 & Windows 10.

**Comment by celeron533** [comment]
Issue is caused by upgrading the nuget packages. Solved in fcef17a252772690bdf8df7af79728ec69bf47f1

**Comment by leosin** [comment]
在v2r下面也是同样遇到这样的问题，fonts.googleapis.com即使在user-rule里面声明了，依然无效，查了下载回来的pac里面确实有@@fonts....这个。目前有什么办法解决吗

**Pull request merged**
