### PR TITLE
update privoxy to 3.0.24

### LINKED ISSUE #455: Privoxy upgrade needed
Privoxy released a new version last month which contains security fixes. Please upgrade built-in privoxy. Thank you for your contributions.

### PR DESCRIPTION
**Pull request by wongsyrone**
The executable was modified based on official release version, which
prevents privoxy from showing tray icon.
jmp dword ptr [<&SHELL32.Shell_NotifyIconA>]  => nop

This should close #455

Signed-off-by: Syrone Wong <wong.syrone@gmail.com>

### CODE REVIEW

**Comment by chenshaoju** [comment]
Virus scan report:
https://www.virustotal.com/en/file/a93c55ee029b2d860ebcfa9a03562c27d0770cf42b0fa3a4ce08ca1d41da6d6d/analysis/1456833996/

https://www.virustotal.com/en/file/85d538063357c66429fa5b373e8bf4ebea0fa39c6b0ec2cd494c5a6c0f45b409/analysis/1456834001/

:+1: Looks good to me, but someone else must approve.

**Comment by wongsyrone** [comment]
BTW, if someone concerns about backdoor or virus, you can use diff tool, such as beyond compare, VBinDiff, etc.

**Comment by GangZhuo** [comment]
Merged

**Comment by wongsyrone** [comment]
:+1:

**Comment by wongsyrone** [comment]
:+1:

**Pull request merged**
