### PR TITLE
add requirement for .NET 4.6.2 in README.md

### PR DESCRIPTION
**Pull request by gitzhuoer**
I tried shadowsocks on Windows 7. However, it didn't work well until I install Microsoft .NET Framework 4.6.2.

### CODE REVIEW

**Comment by celeron533** [comment]
Windows 8 10 也需要安装4.6.2。

**Comment by gitzhuoer** [comment]
Thanks. I use the newest version of Windows 10, so I didn't notice this.

**Comment by celeron533** [comment]
Edited and merged.

**Comment by celeron533** [comment]
no worries, in previous versions of Win 10, 4.6.2 is not delivered within the system.
>Thanks. I use the newest version of Windows 10, so I didn't notice this.

**Pull request closed without merging**
