### PR TITLE
Update zh_CN.txt

### PR DESCRIPTION
**Pull request by zhourinatian**
添加“统计配置”的中文翻译（行70-95）。
Add "Chinese simplification" of Statistics Config (Line 70-95).

## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

- [x] [Searched](https://github.com/shadowsocks/shadowsocks-windows/search?q=is%3Apr&type=Issues) for similar pull requests
- [x] Compiled the code with Visual Studio

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New feature

---

### Description of your *pull request* and other information

Explanation of your *pull request* in arbitrary form goes here. Please make sure the description explains the purpose and effect of your *pull request* and is worded well enough to be understood. Provide as much context and examples as possible.

### CODE REVIEW

**Comment by chenshaoju** [comment]
Thanks for the pull request.

Please wait for developer review.

**Comment by lonelam** [comment]
> * 目前 `Statistics Config` 功能已经很久没维护(存在问题)
> * `Statistics Config` 界面没有相应 I18N 代码支持，当前内容不会生效
> 
> 具体决策看 @celeron533

这功能看起来挺好的呀，具体有什么问题？

**Comment by chenshaoju** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1970

**Comment by studentmain** [comment]
鉴于没有进一步消息，关闭此PR，在#2698中添加了I18N支持

**Pull request closed without merging**
