### PR TITLE
no repeat random number generator

### PR DESCRIPTION
**Pull request by GangZhuo**
The stock code use class Random to generate IV, the Random is pseudo random number generator. The IV maybe repeat, this will cause shadowsocks-libev closed the sockets with the error message 'invalid password or cipher'. Reference https://github.com/shadowsocks/shadowsocks-libev/issues/389

Solution is use class RNGCryptoServiceProvider to generate IV, of course it's lower performance, but a little bit.

### CODE REVIEW

**Comment by bigtan** [comment]
You are right, when I apply your patch, there is no warings like that. While ss-win is not in development now.

**Comment by GangZhuo** [comment]
Yes, when you browse twitter, there are many timeout in the log, the patch can fix these too.

**Comment by GangZhuo** [comment]
Support one-time authorization. You can open it on the "Edit Servers" window.

**Comment by GangZhuo** [comment]
New library libsscrypto2.dll added for one-time authorization, the source code at https://github.com/GangZhuo/libsscrypto2 .

**Comment by GangZhuo** [comment]
If someone wants to try, but can not compile it yourself, you can download from https://github.com/GangZhuo/shadowsocks-windows/releases .

**Comment by icylogic** [comment]
Just merged the random generator part into master. I'll publish 2.5.7 for this fix soon.

**Comment by GangZhuo** [comment]
Great, there are someone to maintain this project.

**Comment by GangZhuo** [comment]
@icylogic  I have no source code for libsscrypto.dll, and I can not add functions to the libsscrypto.dll, so  I create a new library libsscrypto2.dll . If you can update libsscrypto.dll, maybe you can combine the libsscrypto2.dll and libsscrypto.dll to one . 

Thank you very much.

**Comment by icylogic** [comment]
I don't have the source code, either. I'll ask clowwindy.

**Comment by icylogic** [comment]
This project is still in development. I'm working on completing the simple statistics feature. See [this](https://plus.google.com/+%E9%83%AD%E6%98%8A/posts/5K4dr5JcehG) for more details.

@GangZhuo clowwindy says that to create the dll, link these libraries https://github.com/clowwindy/libsodium/tree/stream_min, https://github.com/clowwindy/polarssl/tree/experiment

**Comment by GangZhuo** [comment]
Merged two DLL to one. See changed comment https://github.com/shadowsocks/shadowsocks-windows/pull/313#issuecomment-141629882 .

**Comment by GangZhuo** [comment]
libsscrypto moved to https://github.com/shadowsocks/libsscrypto

**Pull request merged**
