### PR TITLE
Restore user's proxy settings when ss proxy is disabled

### PR DESCRIPTION
**Pull request by xJoeWoo**
Saving user's proxy settings before ss service is enabled and restoring them on program exit.
Fix to #1063 #1078

### CODE REVIEW

**Comment by wongsyrone** [comment]
NAK. You should submit patch to sysproxy project instead of poking registry directly.

**Comment by wongsyrone** [comment]
https://github.com/shadowsocks/sysproxy/blob/master/sysproxy/main.c#L190

**Comment by xJoeWoo** [comment]
Yea, that's the way far more elegant!

**Comment by wongsyrone** [comment]
If you don't want to enable WPAD, just delete `PROXY_TYPE_AUTO_DETECT`

**Comment by xJoeWoo** [comment]
Thanks! What about adding or editing a parameter for non-WPAD off? For example "off all" or something, it's compatible to old commands and offers new function.

**Comment by wongsyrone** [comment]
I'm not sure whether ppl need WPAD or not. The users can disable it themselves via Internet Options in Internet Explorer.

**Comment by xJoeWoo** [comment]
That's what my PR want to do, restoring user's settings :) I would submit to sysproxy project later, and a new commit in here about avoid writing to registry directly.

**Comment by xJoeWoo** [comment]
I patched sysproxy project with two new usage to support this feature. (https://github.com/shadowsocks/sysproxy/pull/1](url)) Windows APIs are used in sysproxy.exe, they helps us to avoid poking registry in ss.
Also, I put record and restore operations into SystemProxy instead of ShadowsocksController. User's proxy settings will be restored as soon as user disable system proxy,

**Comment by xJoeWoo** [comment]
I patched sysproxy project with two new usage to support this feature. https://github.com/shadowsocks/sysproxy/pull/1
Windows APIs are used in sysproxy.exe, they helps us to avoid poking registry in ss.
Also, I put record and restore operations into SystemProxy instead of ShadowsocksController. User's proxy settings will be restored as soon as user disable system proxy,

**Comment by lixingcong** [comment]
Could you please tell me what is the meaning of NAK?

> NAK. You should submit patch to sysproxy project instead of poking registry directly.

**Comment by wongsyrone** [comment]
Negative acknowledgment. In general, it is equivalent to reject.

**Comment by wongsyrone** [comment]
Fixed via https://github.com/shadowsocks/shadowsocks-windows/commit/9ca61defe808efdf1e73966ac47009e54ca574f3

**Pull request closed without merging**
