### PR TITLE
I18n Improvements (rework)

### PR DESCRIPTION
**Pull request by celeron533**
* Fix typo
Remove unexpected empty lines of item [&View] in both Traditional Chinese and Japanese language definitions.

* Uniform the EOL (end of line) style
Convert CF (Unix) to CRLF (Windows) in both Traditional Chinese and Japanese definitions.

* Rename language resources
cn -> zh_CN
zh-tw -> zh_TW
jp -> ja

PS. If you would like to check the details about all languages in future development, you could use the following code:
```
using System;
using System.Globalization;
...
static void Main(string[] args)
{
    // Displays several properties of the neutral cultures.
    Console.WriteLine("CULTURE  ISO ISO WIN DISPLAYNAME                             ENGLISHNAME");
    foreach (CultureInfo ci in CultureInfo.GetCultures(CultureTypes.NeutralCultures))
    {
        Console.Write("{0,-8}", ci.Name);
        Console.Write(" {0,-3}", ci.TwoLetterISOLanguageName);
        Console.Write(" {0,-3}", ci.ThreeLetterISOLanguageName);
        Console.Write(" {0,-3}", ci.ThreeLetterWindowsLanguageName);
        Console.Write(" {0,-40}", ci.DisplayName);
        Console.WriteLine(" {0,-40}", ci.EnglishName);
    }
}
```

### CODE REVIEW

**Comment by wongsyrone** [comment]
LGTM.

**Comment by wongsyrone** [comment]
The only thing I'm not sure about is `name.StartsWith("Japan", StringComparison.OrdinalIgnoreCase)`.
Are you sure it is `Japan` instead of `Japanese`?

**Comment by wongsyrone** [comment]
The standard name is ja-jp.

**Comment by celeron533** [comment]
@wongsyrone , I checked several common used software on my machine and most of them are using `ja` (also using `zh-CN` or `zh_CN`)

image

image

image

image

**Comment by wongsyrone** [comment]
Then `ja` is okay. Just follow the convention.

**Comment by celeron533** [comment]
Checked, it is `Japanese`. Currently it works fine.
> The only thing I'm not sure about is `name.StartsWith("Japan", StringComparison.OrdinalIgnoreCase)`.
> Are you sure it is `Japan` instead of `Japanese`?

**Comment by wongsyrone** [comment]
Yeah. `Japanese` does `StartsWith` `Japan`

**Comment by hellofwy** [comment]
From following pages:

- https://en.wikipedia.org/wiki/Locale_(computer_software)
- https://msdn.microsoft.com/en-us/library/dd373814(v=VS.85).aspx

They use `ISO 639-1` for languages, and `ISO 3166-1` for territories.

- https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
- https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

So your changes about file names are right in my opinion.

**Comment by wongsyrone** [comment]
Thanks for the input.

**Comment by Kiana-Kaslana** [comment]
cn -> zh-CN
zh-tw -> zh-TW
jp -> ja-jp
だと思います。

**Comment by Ruilx** [comment]
Normally uses underline symbol "_" instead of minus symbol "-" eg. "zh_CN"...

**Comment by celeron533** [comment]
@Ruilx , Most of the software uses either`-` or `_`. In my opinion, it's not a problem.
> Normally uses underline symbol "_" instead of minus symbol "-" eg. "zh_CN"...

@Kiana-Kaslana , you could check the screenshots in previous replies and the research by @hellofwy .
> jp -> ja-JP

**Comment by Kiana-Kaslana** [comment]
@celeron533 How can i download this vision?

**Comment by Ruilx** [comment]
@Kiana-Kaslana 
Windows(this project):
SourceCode: https://github.com/shadowsocks/shadowsocks-windows
Bin: https://github.com/shadowsocks/shadowsocks-windows/releases

**Comment by celeron533** [comment]
However, the new version which includes Japanese translation is not built yet.
@Ruilx , currently the CI from appveyor is not activated. So there are no nightly builds available. :disappointed:

> @Kiana-Kaslana
Windows(this project):
SourceCode: https://github.com/shadowsocks/shadowsocks-windows
Bin: https://github.com/shadowsocks/shadowsocks-windows/releases

**Comment by Kiana-Kaslana** [comment]
@celeron533 I see。。。 No Japanese translation.

**Pull request merged**
