### PR TITLE
📐 PAC: add options for direct and proxied groups

### LINKED ISSUE #2984: GeoSite PAC interfere with Windows Store/Windows Feedback/Windows Mail, etc
### Describe the bug
After updating to the latest version, 4.2.0.1, the PAC rules switched to GeoSite, and it seems now it would proxy Microsoft Services to remote server as well. However, I do believe this is not in need in most cases, as MS services generally have localized CDNs. And more importantly, these MS services may no longer work properly behind a remote proxy without MS-based authentication mechanisms. 

### Environment

- Shadowsocks client version: 4.2.0.1
- OS version: Windows 10
- .NET version:

### What did you expect to see?
Whitelist a few MS services from GeoSite PAC

### LINKED ISSUE #2987: 可能geoip数据导致不需要走代理的却走了代理。希望增加域名白名单功能。
- Shadowsocks客户端版本：4.2.1.0
- 操作系统版本：WINDOW10
- .NET版本：4.5+
 
操作步骤
没上网，突然发现在走流量，速度很快，一查日志，在走域名为microsoft的流量，遂发现系统在更新。

期望的结果
无需代理的网址不要走代理

实际结果
更新操作系统在走代理流量

配置文件和日志文件
全新安装，更新了pac, pac模式上网，
配置没问题。

在此粘贴日志
2020-10-14 12:30:49.0379|DEBUG|Shadowsocks.Controller.TCPHandler|connect to 2.tlu.dl.delivery.mp.microsoft.com:80
2020-10-14 12:30:49.0417|DEBUG|Shadowsocks.Controller.TCPHandler|Socket connected to ss server: Bwh-LA 
2020-10-14 12:30:49.2024|DEBUG|Shadowsocks.Controller.TCPHandler|connect to 2.tlu.dl.delivery.mp.microsoft.com:80
2020-10-14 12:30:49.2024|DEBUG|Shadowsocks.Controller.TCPHandler|Socket connected to ss server: Bwh-LA 
2020-10-14 12:30:49.4572|DEBUG|Shadowsocks.Controller.TCPHandler|connect to 2.tlu.dl.delivery.mp.microsoft.com:80
2020-10-14 12:30:49.4572|DEBUG|Shadowsocks.Controller.TCPHandler|Socket connected to ss server: Bwh-LA
2020-10-14 12:30:49.6116|DEBUG|Shadowsocks.Controller.TCPHandler|connect to 2.tlu.dl.delivery.mp.microsoft.com:80

### PR DESCRIPTION
**Pull request by database64128**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

- [x] [Searched](https://github.com/shadowsocks/shadowsocks-windows/search?q=is%3Apr&type=Issues) for similar pull requests
- [x] Compiled the code with Visual Studio
- [ ] Require translation update
- [ ] Require document update (readme.md, wikipage, etc)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [x] New feature

---

### Description of your *pull request* and other information

- Configuration: `geositeDirectGroups` + `geositeProxiedGroups` + `geositePreferDirect`
- PAC: rule generation using these new groups + cleanup
- Closes #2984
- Closes #2987
- Related: #2971, #2973, #2974, #2981, v2fly/domain-list-community#235

#### Notes

- The PAC mode now defaults to whitelist mode.
- `geositeDirectGroups` is initialized with `cn` and `geolocation-!cn@cn`.
- `geositeProxiedGroups` is initialized with `geolocation-!cn`.
- When `geositePreferDirect` is false (default), PAC works in whitelist mode. Exception rules are generated from `geositeDirectGroups`. Unmatched domains goes through the proxy.
- When `geositePreferDirect` is true, PAC works in blacklist mode. Blocking rules are generated from `geositeProxiedGroups`. Exception rules are generated from `geositeDirectGroups`. Unmatched domains are connected to directly.
- The new default values make sure that:
    - When in whitelist mode, Chinese domains, including non-Chinese companies' Chinese CDNs, are connected to directly.
    - When in blacklist mode, only non-Chinese domains goes through the proxy. Chinese domains, as well as non-Chinese companies' Chinese CDNs, are connected to directly.

### CODE REVIEW

**Comment by chenshaoju** [comment]
Base `Shadowsocks-4.2.0.61-Release.exe`, the generated pac.txt is whitelist correctly.

After change `geositePreferDirect` to `true`, The generated pac.txt is blacklist correctly.

But there is an issue: after quit Shadowsocks, changing the `geositePreferDirect` and select update local pac from Geosite, The pac.txt will not update, still old version, and no any information popup from the taskbar tray area.

**Comment by database64128** [comment]
> But there is an issue: after quit Shadowsocks, changing the `geositePreferDirect` and select update local pac from Geosite, The pac.txt will not update, still old version, and no any information popup from the taskbar tray area.

The current behavior is to perform an update of `pac.txt` only when the upstream geosite database updates or it's the first run of a new version. So you're supposed to manually delete `pac.txt` to force a regeneration.

We are targeting v5 for the UI, which will fully support these features. For now, advanced users just have to put up with a few more clicks. 😅

**Review by chenshaoju — APPROVED** [review]
👍 Looks good to me, but someone else must approve.

**Comment by JohnQuick** [comment]
> The new default values make sure that:
> When in whitelist mode, Chinese domains, including non-Chinese companies' Chinese CDNs, are connected to directly.
> When in blacklist mode, only non-Chinese domains goes through the proxy. Chinese domains, as well as non-Chinese companies' Chinese CDNs, are connected to directly.

What's the difference of those two mode? Both modes state that "Chinese domains, as well as non-Chinese companies' Chinese CDNs, are connected to directly."
And there's no definition of "Chinese domains" and "non-Chinese domains".
And why are you determining whether it's a Chinese domain or not? Users only care whether this domain is accessible directly or not, no matter which category it's in.

**Pull request merged**
