### PR TITLE
Removed unused array allocations

### PR DESCRIPTION
**Pull request by DamirAinullin**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

- [x] [Searched](https://github.com/shadowsocks/shadowsocks-windows/search?q=is%3Apr&type=Issues) for similar pull requests
- [x] Compiled the code with Visual Studio

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New feature

---

### Description of your *pull request* and other information

Removed unused array allocations in order to decrease memory traffic.

### CODE REVIEW

**Comment by celeron533** [comment]
Leave it as a place holder.

**Comment by DamirAinullin** [comment]
@celeron533 Can you explain a bit more please? What do you mean by place holder? This array is not used at all I suppose.

**Comment by celeron533** [comment]
Hi @DamirAinullin , thanks for pointed out this. Yes, this array's initial size is not so import because it would be overwritten by other methods or variable.

**Comment by celeron533** [comment]
@DamirAinullin sorry for the misleading in previously closed the pr

**Pull request merged**
