### PR TITLE
Fix user rule

### LINKED ISSUE #894: 程序运行时修改自定义规则 user-rule.txt 导致程序崩溃
### Version(release version or AppVeyor link)
3.3.5

### Environment(Operating system, .NET Framework, etc)
win7 .NET Framework 4.6.2

### Steps you have tried
1.正常使用程序
2.修改user-rule.txt ，保存

### What did you expect to see?
正常运行

### What did you see instead?
shadowsockswinbug

### PR DESCRIPTION
**Pull request by 772807886**
Fix #894, #951
* Repair the occasional abnormal exit problem when saving the user-rule.txt file.
* Adds a menu item for manually updating user rule file.

### CODE REVIEW

**Comment by 772807886** [comment]
AppVeyor：https://ci.appveyor.com/project/LimingJin/shadowsocks-windows/build/3.3.41

**Comment by 772807886** [comment]
AppVeyor: https://ci.appveyor.com/project/LimingJin/shadowsocks-windows/build/3.4.2

**Comment by breakwa11** [comment]
不如担心一下什么时候能merge。。。

**Comment by celeron533** [comment]
因为原来设定的AppVeyor挂了 #956
> P.S. 话说为什么没有PullRequest的自动编译检查了。。。

**Comment by wongsyrone** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/894#issuecomment-268948118

**Pull request closed without merging**
