### PR TITLE
Add OpenSSL 1.1.0g support due to hardware acceleration

### PR DESCRIPTION
**Pull request by wongsyrone**
Note: If you want to compile it by yourself, please make sure
do NOT use `no-asm` configure option, since the main point of
this commit is to utilize assembly in openssl

Please test all encrypton method before merging.

### CODE REVIEW

**Comment by wongsyrone** [comment]
@madeye @celeron533 
Please test

**Comment by wongsyrone** [comment]
One should install Microsoft Visual C++ runtime, otherwise, dllnotfoundexception may occur.

virus report: https://www.virustotal.com/#/file/d8cd854e7652283c3d1eb332f8a8ff7580c19ebdbfbc1a313cc6ca38be169f95/details

As you see, it depends on 

```
ADVAPI32.dll
KERNEL32.dll
USER32.dll
VCRUNTIME140.dll
WS2_32.dll
api-ms-win-crt-convert-l1-1-0.dll
api-ms-win-crt-environment-l1-1-0.dll
api-ms-win-crt-filesystem-l1-1-0.dll
api-ms-win-crt-heap-l1-1-0.dll
api-ms-win-crt-math-l1-1-0.dll
api-ms-win-crt-runtime-l1-1-0.dll
api-ms-win-crt-stdio-l1-1-0.dll
api-ms-win-crt-string-l1-1-0.dll
api-ms-win-crt-time-l1-1-0.dll
api-ms-win-crt-utility-l1-1-0.dll
```

**Comment by chenshaoju** [comment]
The quick test is OK, Base on AppVeyor 4.0.7.14.
:+1: Looks good to me, but someone else must approve.

**Comment by celeron533** [comment]
Thanks @wongsyrone @chenshaoju 
I will test all supported encryption methods and pick some of them to download a 2.1GB single file.

**Comment by celeron533** [comment]
Tested with Python version of ss 3.0.0 server on Windows

method => lib | notes
--------------------- | -----
aes-128-cfb=>StreamOpenSSLEncryptor | pass
aes-192-cfb=>StreamOpenSSLEncryptor | pass
aes-256-cfb=>StreamOpenSSLEncryptor | pass (with 2GB file transfer)
aes-128-ctr=>StreamOpenSSLEncryptor | pass
aes-192-ctr=>StreamOpenSSLEncryptor | pass
aes-256-ctr=>StreamOpenSSLEncryptor | pass (with 2GB file transfer)
bf-cfb=>StreamOpenSSLEncryptor | **FAIL?**
camellia-128-cfb=>StreamOpenSSLEncryptor | pass
camellia-192-cfb=>StreamOpenSSLEncryptor | pass
camellia-256-cfb=>StreamOpenSSLEncryptor | pass (with 2GB file transfer)
rc4-md5=>StreamOpenSSLEncryptor | pass (with 2GB file transfer)
salsa20=>StreamSodiumEncryptor | _Not Tested_
chacha20=>StreamSodiumEncryptor | _Not Tested_
chacha20-ietf=>StreamSodiumEncryptor | _Not Tested_
aes-128-gcm=>AEADOpenSSLEncryptor | pass
aes-192-gcm=>AEADOpenSSLEncryptor | pass
aes-256-gcm=>AEADOpenSSLEncryptor | pass (with 2GB file transfer)
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor | _Not Tested_

**Comment by wongsyrone** [comment]
It doesn't matter, in the next OpenSSL release, some weak ciphers' assembly will be [removed](https://github.com/openssl/openssl/pull/5320) and we can remove these entries.

Any test from ss-libev? There are several issues in the python one.
BTW, I don't think there is anyone using bf-cfb.

**Comment by wongsyrone** [comment]
Only entries with "OpenSSLEncryptor" needs testing. That's why I expose encryptor info.

**Comment by wongsyrone** [comment]
@celeron533 I pushed a cipher name fix, it should work now. chacha20-ietf-poly1305 is tested on my side.

**Comment by celeron533** [comment]
@wongsyrone 
bf-cfb=>StreamOpenSSLEncryptor    **PASS**

**Pull request merged**
