### PR TITLE
bug fix for missing data

### PR DESCRIPTION
**Pull request by ihciah**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

- [x] [Searched](https://github.com/shadowsocks/shadowsocks-windows/search?q=is%3Apr&type=Issues) for similar pull requests
- [x] Compiled the code with Visual Studio

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New feature

---

### Description of your *pull request* and other information

It may lost data when receiving the first packet from remote. For example, using stream cipher, if the length of the first packet received is shorter than IV, it will be discarded.

### CODE REVIEW

**Comment by ihciah** [comment]
I found the fix cannot fix the problem...
Will open another pr soon.

**Comment by wongsyrone** [comment]
> if the length of the first packet received is shorter than IV, it will be discarded.

They are stored in the internal circular buffer, no matter what kind of method you are using, stream or AEAD. We apply greedy strategy to handle AEAD decryption.

**Comment by ihciah** [comment]
> > if the length of the first packet received is shorter than IV, it will be discarded.
> 
> They are stored in the internal circular buffer, no matter what kind of method you are using, stream or AEAD. We apply greedy strategy to handle AEAD decryption.

I don't understand why not saving the received data if it's too short.
For example, if the data arrived byte-by-byte(one cannot promise the tcp data recv as send), they will all be discarded.
I think the data should be saved and appended, until the length is enough for decrypting.

Thanks for your reply.

**Comment by ihciah** [comment]
> > if the length of the first packet received is shorter than IV, it will be discarded.
> 
> They are stored in the internal circular buffer, no matter what kind of method you are using, stream or AEAD. We apply greedy strategy to handle AEAD decryption.

I got it.
Thanks for your reply.

**Pull request closed without merging**
