### PR TITLE
Fix the many "HTTP Auto Proxy Detection Worker Process" bugs in Windwws 10 Version 1809

### LINKED ISSUE #1979: Windows 10 RS5，当处于 PAC 模式时，每次睡眠唤醒后都多出一个 pacjsworker.exe 进程
也许与 RS5 的新沙盒有关。https://twitter.com/epakskape/status/1007316208087994368

### Shadowsocks version / 影梭版本
4.1.1

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Windows 10 build 17741

### Steps you have tried / 操作步骤
1. 切换到 PAC 模式
2. Windows 选择睡眠，然后重新登陆

### What did you expect to see? / 期望的结果
不要新出现 pacjsworker.exe

### What did you see instead? / 实际结果
新出现了一个 pacjsworker.exe

### PR DESCRIPTION
**Pull request by tlanyan**
Fix #1979.

If you can read Chinese, please refer  [系统出现大量HTTP Auto Proxy Detection Worker Process](https://tlanyan.me/many-http-auto-proxy-detection-worker-processes/) for more details.

## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

- [v] [Searched](https://github.com/shadowsocks/shadowsocks-windows/search?q=is%3Apr&type=Issues) for similar pull requests
- [v] Compiled the code with Visual Studio

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New feature

---

### Description of your *pull request* and other information

Changes has been compiled and tested. You can download and try the modified windows binary: [Shadowsocks-4.1.4-tlanyan2.zip](https://github.com/tlanyan/shadowsocks-windows/files/2837521/Shadowsocks-4.1.4-tlanyan2.zip)

### CODE REVIEW

**Comment by chenshaoju** [comment]
Tested base Appveyor [4.1.4.3](https://ci.appveyor.com/project/celeron533/shadowsocks-windows/build/job/u1cvy0j75im8cmxm/artifacts) version has passed.

But I'm not sure after the user edited pac.txt or user-rule.txt still can apply to system immediately.

**Comment by tlanyan** [comment]
I'm (very) sure it works after the user updated pac.txt or user-rule.txt, since I didn't modify the file change handler

**Comment by celeron533** [comment]
Thanks @tlanyan to send this pull request and share your discoveries on the blog.

So the code logic in this pull request only initiate the PAC server and address on start up only. And the timestamp should be always the same to avoid redundant "HTTP Auto Proxy Detection Worker Process".

However, once the PAC url is initiated, it cannot be updated.
Scenario 1:
What if user enabled "Secure Local PAC" or disable "Secure Local PAC" again to add/remove `secret` in the query string?
Scenario 2:
What if user change the local port.

The timestamp is designed to force browser to always update the cache to use the PAC content with the latest version. However, since we have implemented the "watch PAC/userrule file change" on the fly, the timestamp may become useless in some of the use cases.

**Comment by tlanyan** [comment]
@celeron533 
Thanks for your kind remind. 

For Scenario 1, it's unnecessary to remove the query string in the PAC URL. The executable will work well with or without the "Secure Local PAC" function.

For Scenario 2, the user must quit and reboot the program.

In any case, a new PAC url to the LAN setting will lead to a new "HTTP Auto Proxy Detection Worker Process", until MS fix the watch behavior.

**Comment by studentmain** [comment]
微软怎么说

**Comment by tlanyan** [comment]
I suggested another fix in my blog post   [系统出现大量HTTP Auto Proxy Detection Worker Process](https://tlanyan.me/many-http-auto-proxy-detection-worker-processes/),  which works for both Scenario  1 and Scenario 2. 

The fix is:

````
// file： shadowsocks-csharp\Controller\Service\PACServer.cs
public void UpdateConfiguration(Configuration config)
{
this._config = config;

if (config.secureLocalPac)
{
// comment this part
// var rd = new byte[32];
// RNG.GetBytes(rd);
// PacSecret = $"&secret={Convert.ToBase64String(rd)}";
// PAC_SECRET_FILE is class const with value "pac-secure.txt"
if (!File.Exists(PAC_SECRET_FILE))
{
  var rd = new byte[32];
  RNG.GetBytes(rd);
  string secret = Convert.ToBase64String(rd);
  PacSecret = $"secret={secret}";
  File.WriteAllText(PAC_SECRET_FILE, secret);
}
else
{
  PacSecret = $"secret={File.ReadAllText(PAC_SECRET_FILE)}";
}
}
else
{
PacSecret = "";
}
// remove timestamp
// PacUrl = $"http://127.0.0.1:{config.localPort}/pac?t={GetTimestamp(DateTime.Now)}{PacSecret}";
PacUrl = $"http://127.0.0.1:{config.localPort}/pac?{PacSecret}";
}
````

**Comment by celeron533** [comment]
所以这个pull request到底是为了解决pacjsworker.exe还是自定义config？

**Comment by tlanyan** [comment]
我的锅。

本来应该是两个pull request，提交代码时没有建feature分支，自定义config的代码直接就推到了master分支

**Comment by database64128** [comment]
实测，最新预览版18334仍然存在pacjsworker的问题，指望微软修复基本是不可能了。

**Comment by tlanyan** [comment]
我博客里说了，微软未必认为pacjsworker的行为是bug

**Comment by database64128** [comment]
> 我博客里说了，微软未必认为pacjsworker的行为是bug

你博客里并没有提到这一点，只提到了“另外我不认为这是巨硬的锅，他们未必会修复”。你也没有引述任何来自微软或微软开发人员的言论来证实这一说法/猜想。
针对旧的已弃用的PAC的进程不退出而产生堆积，如果这都不是bug，难道这么多年我对bug这个词的理解不对？

**Comment by celeron533** [comment]
方案一：去掉timestamp。会导致windows不能及时更新缓存过的pac内容。
方案二：仅生成一次PAC地址。不但会有方案一的问题，还会导致监听端口变化后PAC地址不变，除非重启ss。
维持现状：海量pacjsworker。
巨硬：你说什么我听不见。

头大。

**Comment by tlanyan** [comment]
我没细看工程代码，只记得里面有文件变化监听的handler. 照你这么一说，我大概知道文件更新后其实是通过`UpdateConfiguration`函数来刷新PAC缓存

依目前情形看，采用方案一，文件更新后重新生成key保存到`pac-secret.txt`文件, 也许是一个稳妥的办法

**Pull request closed without merging**
