### PR TITLE
allow modifying privoxy listen port

### PR DESCRIPTION
**Pull request by shenm233**

### CODE REVIEW

**Comment by breakwa11** [comment]
为什么要弄这个

**Comment by wongsyrone** [comment]
你直接指定使用ss的监听端口就行了

**Comment by shenm233** [comment]
没注意到ss监听的端口支持http代理

**Comment by wongsyrone** [comment]
https://github.com/shadowsocks/shadowsocks-windows/blob/master/shadowsocks-csharp/Controller/Service/Listener.cs#L205

https://github.com/shadowsocks/shadowsocks-windows/blob/master/shadowsocks-csharp/Controller/ShadowsocksController.cs#L472-L476

**Pull request closed without merging**
