### PR TITLE
🎃 PAC: workaround to exempt private IP ranges in whitelist mode

### LINKED ISSUE #3002: 新版本PAC会代理局域网地址
### 简要描述问题
启用PAC模式后，会代理私网地址
如10.*.*.*./172.16.*.*/192.168.*.*的网段
手动在user-rule.txt中添加
@@||10.*.*.*.
@@||172.16.*.*
@@||192.168.*.*
问题解决
### 环境

- Shadowsocks客户端版本：4.3.0.0
- 操作系统版本：Windows10 2004 19041.572

### 期望的结果
希望PAC文件中自动添加对于IPv4/IPv6相关的私网地址规则规避

### PR DESCRIPTION
**Pull request by database64128**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

- [x] [Searched](https://github.com/shadowsocks/shadowsocks-windows/search?q=is%3Apr&type=Issues) for similar pull requests
- [x] Compiled the code with Visual Studio
- [ ] Require translation update
- [ ] Require document update (readme.md, wikipage, etc)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New feature

---

### Description of your *pull request* and other information

- Could match domains with similar patterns. But that's all we can do for now.
- No active developers use PAC mode. We are looking to deprecate PAC in favor of routing solutions.
- Closes #3002.

### CODE REVIEW

**Comment by darkflame0** [comment]
Missing localhost.

**Comment by chenshaoju** [comment]
@darkflame0 https://github.com/shadowsocks/shadowsocks-windows/blob/589abf0e9ed52d05e38db4e73eae2806a48e441e/shadowsocks-csharp/Util/SystemProxy/Sysproxy.cs#L22

**Comment by Loyalsoldier** [comment]
https://github.com/v2fly/geoip/blob/3f2e0c5d1febd8e0580fb986d6f76ebd3209a9ff/main.go#L28-L48

https://github.com/v2fly/domain-list-community/blob/16abfd4399b25f665f051ac337dfe9edec8e5fe4/data/private

BTW, should set `geositePreferDirect ` to `true` by default, or use geosite with DNS resolving process to judge the IP.

**Comment by chenshaoju** [comment]
The quick test is passed, private IP (192.168.1.0/24 in my case) can working with `"geositePreferDirect": false,` and `"geositePreferDirect": true,` .

:+1: Looks good to me, but someone else must approve.

**Pull request merged**
