### PR TITLE
Implement "Show Plugin Output" checkbox.

### PR DESCRIPTION
**Pull request by rwasef1830**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

- [x] [Searched](https://github.com/shadowsocks/shadowsocks-windows/search?q=is%3Apr&type=Issues) for similar pull requests
- [x] Compiled the code with Visual Studio

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New feature

---

This is a simple improvement that allows viewing the plugin output window instead of always hiding it. It can be very useful to debug plugin issues instead of being forced to duplicate the config and run the plugin standalone just to see its output.

### CODE REVIEW

**Comment by chenshaoju** [comment]
Thanks for the send pull request, Please wait for the developer review the code. 😇

**Comment by studentmain** [comment]
Pass all test first

**Comment by rwasef1830** [comment]
@studentmain all tests pass now, my apologies. now it is failing due to unrelated problem with mbedtls test.

**Comment by studentmain** [comment]
Maybe redirect plugin's stdout into log?

Plugin's window can closed by user, which cause plugin exit.

**Comment by rwasef1830** [comment]
Each plugin may have its own way of logging which can be set using plugin arguments. Also no problem if the user closed the plugin window, it will be automatically restarted, so it's not a problem in my opinion.

This is just a simple switch to see the output of the plugin just in case the plugin displayed any messages useful for troubleshooting. It is meant to be used temporarily. And it can accomodate any complicated console output of any plugin.

To make it log to file will complicate things a little (need to log stdout and stderr), stdout or stderr might use non printable characters ... plugin may have its own logging... etc.

What do you think ?

**Comment by studentmain** [comment]
> it's not a problem in my opinion.

Yes, it's not a big problem. The feature is ok (if user know what they did).

Consider what happened in plugin command line inputbox (#2212), I suggest put the switch in right click menu > "Help", just like verbose logging switch.

**Comment by rwasef1830** [comment]
@studentmain The reason why I put the checkbox in that dialog is to allow the user to press Apply and cause restart of the plugin with the restart of the server. If I put it in right-click, and the user choose it, it will not do any effect, and I don't want to cause restart of the server unnecessarily by right-click menu.

This way, all the option that cause restart of the server and plugin are in 1 place (the server config window) and it makes more sense for the user without any surprises. Because the user already expects that the server will be restarted when they press Apply or Ok and we want this to happen when they change the "Show plugin output" setting.

What do you think ?

**Comment by studentmain** [comment]
> If I put it in right-click, and the user choose it, it will not do any effect

Just reload controller in callback function.

>  all the option that cause restart of the server and plugin are in 1 place

This feature is for debugging, so I'd like put it near other debugging option. BTW, server also restart when we toggle system proxy mode......

**Comment by rwasef1830** [comment]
@studentmain Done. It is now as you described to me. Help > Show Plugin Output

**Comment by studentmain** [comment]
Looks good to me, thank you.

**Comment by celeron533** [comment]
A very good way for debugging and tracing error

**Comment by studentmain** [comment]
@celeron533 Let's merge them?

**Pull request merged**
