### PR TITLE
Show underline in PasswordTextBox

### LINKED ISSUE #2406: 明显标注密码首尾的空白字符
大家的报错基本都是
“System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。  有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。”
类似这样的，然后无论是远程还是本地端口测试也好，ip测试也好都是通的。我今天在一台新的电脑上部署客户端也发生了这个问题，然后我就在这里爬文，作者提供的各种方法都试了一次。最后都无效，最后的最后发现，问题出在密码上，由于密码都是复杂化的，每次都是偷懒复制黏贴进去，虽然开着显示密码确认，但其中有一个非常容易被忽视的，那就是空格。我发现空格是可以保存的。。。去掉空格后，一切正常了。。
所以希望作者是否可以在密码输入框对空格进行校验，免得再有相同的粗心人中招。

### PR DESCRIPTION
**Pull request by studentmain**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

- [x] [Searched](https://github.com/shadowsocks/shadowsocks-windows/search?q=is%3Apr&type=Issues) for similar pull requests
- [x] Compiled the code with Visual Studio
- [ ] Require translation update
- [ ] Require document update (readme.md, wikipage, etc)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New feature

---

### Description of your *pull request* and other information

Close #2406

图片

### CODE REVIEW

**Comment by celeron533** [comment]
Feel this requirement change is unnecessary from my point of view.
1. It is rare to happen for most of the users
2. If user always experiencing the leading or trailing space issue, there are some usability problem from the copy-paste source.
3. When user has an underscore in password, will it be more difficult to observe in new design?
4. Referencing from other software's "show password " design, they must noticed the similar scenario but do  "nothing".

**Comment by studentmain** [comment]
Will use monospace font in password box instead

**Comment by celeron533** [comment]
> Will use monospace font in password box instead

good idea

**Comment by studentmain** [comment]
图片

I changed all textbox for better looking.

**Pull request closed without merging**
