### PR TITLE
bump 3.0

### PR DESCRIPTION
**Pull request by GangZhuo**

### CODE REVIEW

**Comment by chenshaoju** [comment]
Statistics may have some issue can case shadowsocks.exe crash at long time running.

The re-test is running,need less 24 hour for test.

**Comment by GangZhuo** [comment]
I think @icylogic test already, he told me we can release 3.0

**Comment by chenshaoju** [comment]
It's a bit hard for recurrent,Here is Windows crash report:

Version is 1.0.11２

> 描述
错误的应用程序路径:	D:\Software\Shadowsocks\Shadowsocks.exe

>问题签名
问题事件名称:	CLR20r3
问题签名 01:	Shadowsocks.exe
问题签名 02:	2.5.8.2
问题签名 03:	56d5b4a5
问题签名 04:	mscorlib
问题签名 05:	4.6.1055.0
问题签名 06:	563c0eac
问题签名 07:	3694
问题签名 08:	10
问题签名 09:	A4DH5WWIWWW1YJTMP0C0KV4ZWCALU4IN
OS 版本:	6.1.7601.2.1.0.768.3
区域设置 ID:	2052
其他信息 1:	0a9e
其他信息 2:	0a9e372d3b4ad19135b953a78882e789
其他信息 3:	0a9e
其他信息 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by GangZhuo** [comment]
Can you create a crash dump file, when it happen again? 
See http://stackoverflow.com/questions/4992569/how-do-i-obtain-a-crash-dump . 

Note: Change your passwords after upload dump file.

**Comment by chenshaoju** [comment]
It a bit hard for change all password,My shadowsocks have less 10 servers.
Can I send the dump to your E-mail address? I'm now testing 3.0 public version.

**Comment by GangZhuo** [comment]
@chenshaoju  Yes, welcome.

**Comment by chenshaoju** [comment]
@GangZhuo I already send 2 dump files to your gmail inbox,Mar 22 and Mar 28(today). I'm start test Newest version on appveyor,If need more anythings Please let' me know. :)

**Pull request merged**
