### PR TITLE
fix #2140

### LINKED ISSUE #2140: PAC 规则对于某些网址不生效，以及浏览器不能实时更新的问题
● Shadowsocks version / 影梭版本
4.1.2

● Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win7 Sp1

● Steps you have tried / 操作步骤
1、在user-rule.txt中写入「||ip.cn」，见下图

2、重启「系统代理」（可以看到pac文件确实改变了，但是浏览器好像并没有使用的新pac规则，如果可以的话，这个问题可否回答下？）
3、再次打开「https://ip.cn」，但是ip地址仍然是我本机的ip，而不是远程服务器的ip，见下图

● What did you expect to see? / 期望的结果
显示远程服务器ip，就像我使用「全局代理」模式下的显示，见下图

● What did you see instead? / 实际结果
就像没有使用使用代理访问一样

● Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
我认为和此项关系不大，因为类似的查询ip的网站如「https://www.iplocation.net/」类似设置是可以生效的。

PS: 这问题让我一度很奇怪，希望尽快收到作者的回复。

### PR DESCRIPTION
**Pull request by lucksevenl7**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

- [ ] [Searched](https://github.com/shadowsocks/shadowsocks-windows/search?q=is%3Apr&type=Issues) for similar pull requests
- [x] Compiled the code with Visual Studio

### What is the purpose of your *pull request*?
- [ x] Bug fix
- [ ] Improvement
- [ ] New feature

---

### Description of your *pull request* and other information

fix [issues#2140](https://github.com/shadowsocks/shadowsocks-windows/issues/2140)
now,when change "pac.txt" or "user-rule.txt" will take effect immediately，no need to manually click enable system proxy option.

### CODE REVIEW

**Comment by celeron533** [comment]
What you need is `UpdateSystemProxy();`

**Comment by lucksevenl7** [comment]
@celeron533 I have tried version 4.1.3 and this bug still exist..

**Comment by celeron533** [comment]
@lucksevenl7 Could you please try this:
https://github.com/celeron533/shadowsocks-windows/commit/5ffb7c4ca5d06d665de642c83da0b2ce160aa3ce

**Comment by lucksevenl7** [comment]
@celeron533 [celeron533@5ffb7c4](https://github.com/celeron533/shadowsocks-windows/commit/5ffb7c4ca5d06d665de642c83da0b2ce160aa3ce) is work .
I  has test this feature with [ip138.com](http://www.ip138.com/)

**Pull request closed without merging**
