### PR TITLE
PerMonitorV2 DpiAwareness

### LINKED ISSUE #2426: Per-monitor DPI awareness
### Shadowsocks version / 影梭版本

4.1.6

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）

Windows 10 1903

### Steps you have tried / 操作步骤

1. Have two monitors with different DPI set
2. Drag any window of this application to the other monitor

### What did you expect to see? / 期望的结果

Rescale for the new DPI

### What did you see instead? / 实际结果

No changes

P.S. Status bar icon also does not seem to respond to DPI change.

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）

Not relevant

Related doc: https://docs.microsoft.com/en-us/windows/desktop/hidpi/high-dpi-desktop-application-development-on-windows

I will try to submit a PR later if I managed to fix this.

### PR DESCRIPTION
**Pull request by Mygod**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

- [x] [Searched](https://github.com/shadowsocks/shadowsocks-windows/search?q=is%3Apr&type=Issues) for similar pull requests
- [x] Compiled the code with Visual Studio

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New feature

---

### Description of your *pull request* and other information

Also fixes #2426.

Warning: Ugly.

### CODE REVIEW

**Comment by Mygod** [comment]
I think Microsoft has given up on Windows Forms, and so have I.

**Comment by celeron533** [comment]
```
Discovering tests...OK
vstest.console /logger:Appveyor "C:\projects\shadowsocks-windows\test\bin\x86\Release\test.dll"
'vstest.console' is not recognized as an internal or external command,
operable program or batch file.
Command exited with code 1
```

It seems default Appveyor cannot find vstest.console.
(I've update the build image to VS2019 for other pull requests)

**Comment by Mygod** [comment]
Should I change build target to 4.7.2 instead of 4.8? I think both should work.

**Comment by celeron533** [comment]
> I think Microsoft has given up on Windows Forms, and so have I.

Perhaps a better 
* WPF UI
* Entry point (a simplified socks5 services written in C#, could be replaced by an virtual NIC like openvpn)
* Load manager/balancer (speed monitor, determine domestic/international transmission, auto switch servers/tunnels)
* Crypt Tunnels (servers). Not only the original shadowsocks implementations, but also able to connect to 3rd vendors such as kcptun.
* Plugin support.
* All components above could be connected by loop-backs. To reduce port conflict, could use `127.0.0.2` as the loop-back interface.

**Comment by celeron533** [comment]
@Mygod build passed. Weird thing is appveyor cannot execute the tests.

**Comment by Mygod** [comment]
@celeron533 You mean basically rewrite the entire repo.

My suggestion is to take the quickest fix #2427 instead because this fix introduces more bugs than it solves and I have absolutely no idea why.

**Comment by Mygod** [comment]
@celeron533 Maybe consider .NET Core instead. .NET Framework [is](https://visualstudiomagazine.com/articles/2018/10/10/net-keynote.aspx) [dead](https://betanews.com/2019/05/07/future-of-dotnet/) and [buggy with shitty support](https://news.ycombinator.com/item?id=8121737) (and I can confirm this back even when it was not as dead). Don't bother with WPF.

**Comment by studentmain** [comment]
closed by #2877

**Pull request closed without merging**
