### PR TITLE
a lot of commits

### PR DESCRIPTION
**Pull request by kimw**
It's a lot of commits since Aug, 2015.

--- updated 1/5/16
* SimpleJson => Newtonesoft.Json
* bandwidth counted

### CODE REVIEW

**Comment by chenshaoju** [comment]
:+1: Looks good to me,but someone else must approve.

**Comment by wongsyrone** [comment]
It will be better if commits get squashed.

**Comment by GangZhuo** [comment]
@kimw  Can you update the code for: If a Log Form already opened, then active the Form instead of open a new Log Form?

**Comment by kimw** [comment]
@GangZhuo It's a feature that the users/developers can view logs in seperated windows. Sometimes, it's usefull while the logs are rolling fast. On this feature, people can let a log rolling happylly in one logViwer window as it be (e.g. watching the newest messages), and stare on another non-rolling logViwer. It's very usefull at the time we trying to finger out network problems, that's what the logs main function I think so.

Nonetheless, if you insist on single-log-window feature, I can code it as an option. But, I keep my opinions.

Expecting your words.
---
Kim

**Comment by GangZhuo** [comment]
@kimw Ok, you are right.

**Comment by GangZhuo** [comment]
Merged. Thanks.

**Pull request merged**
