### PR TITLE
deprecate unsafe encryption method

### LINKED ISSUE #2715: Remove bf-cfb, chacha20, salsa20, rc4-md5
According to spec:

> Implementors are advised to remove them as soon as possible.

移除 bf-cfb, chacha20, salsa20, rc4-md5

按照标准：实现应当尽快移除它们。

### PR DESCRIPTION
**Pull request by studentmain**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

- [x] [Searched](https://github.com/shadowsocks/shadowsocks-windows/search?q=is%3Apr&type=Issues) for similar pull requests
- [x] Compiled the code with Visual Studio
- [x] Require translation update
- [ ] Require document update (readme.md, wikipage, etc)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New feature

---

### Description of your *pull request* and other information

Close #2715, some heavy modify in ConfigForm.cs in order to show deprecated warning in EncryptionSelect

### CODE REVIEW

**Comment by Prajwal-Koirala** [comment]
+1

**Comment by celeron533** [comment]
I may rewrite the entire config form in data binding pattern in the coming weeks. （咕咕咕）

**Comment by studentmain** [comment]
> 
> 
> I may rewrite the entire config form in data binding pattern in the coming weeks. （咕咕咕）

Let's discuss it in v5 update plan?

**Comment by celeron533** [comment]
> Let's discuss it in v5 update plan?

sure

**Comment by celeron533** [comment]
@studentmain you could merge this pull request if you are confident.

**Comment by celeron533** [comment]
Rebased the code and add new translations.

**Comment by chenshaoju** [comment]
Redirect attack on Shadowsocks stream ciphers https://github.com/edwardz246003/shadowsocks

**Comment by studentmain** [comment]
> 
> 
> Redirect attack on Shadowsocks stream ciphers https://github.com/edwardz246003/shadowsocks

Let's depercate them in v5 then.

**Comment by studentmain** [comment]
Or more aggressive, deprecate them now, and delete them in v5?

**Comment by celeron533** [comment]
> deprecate them now, and delete them in v5?

Argee

**Pull request merged**
