### PR TITLE
add xchacha20-ietf-poly1305

### PR DESCRIPTION
**Pull request by wongsyrone**
- update mbedtls to 2.7.0, use new md5 api
- update libsodium to 1.0.16
- static link to openssl 1.1.0g, check libsscrypto repo for detail

### CODE REVIEW

**Comment by wongsyrone** [comment]
check https://github.com/shadowsocks/libsscrypto/pull/7 for detail

**Comment by wongsyrone** [comment]
Close due to no response.

**Comment by chenshaoju** [comment]
@celeron533 表个态呗。。。libev是支持了的。

**Comment by celeron533** [comment]
> Close due to no response.

@wongsyrone  昨天刚拉了代码，还在review，最近事情太多

**Comment by celeron533** [comment]
oh, both repos have been removed. :worried:

**Comment by pexcn** [comment]
试了一下，运行良好~

**Comment by wongsyrone** [comment]
You can `git am` the patches on the corresponding repo.

https://drive.google.com/open?id=1G2Ifjcx_V2-ygmqQoMz3B4Wui5e_s_3J

**Comment by celeron533** [comment]
thanks @wongsyrone 
Sorry for the late response.

**Pull request closed without merging**
