### PR TITLE
Fix #2458 Unexpected delete server behavior

### LINKED ISSUE #2458: 4.1.7 删除按钮有严重的问题 / Delete button issue
### Shadowsocks version / 影梭版本
4.1.7

现在的效果是点删除，会删掉选中的下面的那个，并且跳到最后一项。

`UpdateIndexToEnd();`前一行还是正常的，执行完这个函数后没有的就是选中的下面一项了。

应该是 https://github.com/shadowsocks/shadowsocks-windows/pull/2410/files?file-filters%5B%5D=.cs&file-filters%5B%5D=.yml#diff-411c02bb9a33cb67be83f9fd7aa03dcc 引入的。

### PR DESCRIPTION
**Pull request by Stzx**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

- [x] [Searched](https://github.com/shadowsocks/shadowsocks-windows/search?q=is%3Apr&type=Issues) for similar pull requests
- [x] Compiled the code with Visual Studio

### What is the purpose of your *pull request*?
- [x] Bug fix
- [x] Improvement
- [ ] New feature

---

### Description of your *pull request* and other information

修复删除时事件触发导致，错误的删除。

修改服务器列表位置调整逻辑，与 `4.16` 版本保持一致。

Explanation of your *pull request* in arbitrary form goes here. Please make sure the description explains the purpose and effect of your *pull request* and is worded well enough to be understood. Provide as much context and examples as possible.

### CODE REVIEW

**Comment by imba-tjd** [comment]
嗯，这样是可以删掉正确的条目，但是还是会跳到最后一项。你试一下4.1.6的效果

**Comment by imba-tjd** [comment]
忽然发现，复制也应该是差不多的逻辑，就在下一个地方生成重复的条目。现在4.1.7变成了在最后生成。

**Comment by Stzx** [comment]
删除可以考虑保留当前位置，复制的话由于会定位到复制的位置，倒是没什么关系。

你觉得呢？ @imba-tjd

**Comment by imba-tjd** [comment]
我个人意见是和4.1.6的行为保持一致……

**Pull request merged**
